version: '3'
#Backend
services:
  smart-brain-api:
    build: ./
    ports:
      - "5000:5000"
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    volumes:
      - ./:/usr/src/smart-brain-api
      - /usr/src/smart-brain-api/node_modules
    command: npm start

  
#Postgres
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres


#Redis
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"



      